[package]
name = "leema"
version = "0.0.1"
authors = ["Matthew Graham <mdg149@gmail.com>"]
rustc-link-search = ["."]
rustc-link-lib = ["leemalex"]

[[bin]]
name = "leema"

[dependencies]
bytes = "0.4.5"
futures = "0.1"
libc = "0.2"
log = "0.3.3"
docopt = "0.6"
mopa = "0.2.2"
rand = "0.3"
rustc-serialize = "0.3"
tokio = "0.1"
tokio-current-thread = "0.1"
